name: My frist workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: list and read files
          run: |
            echo "my first github action"
            ls -ltra
            cat README.md

        - name: Generate ASCII artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR" >> dragon.txt